kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  annotations:
  name: openshift-rabbitmq
  namespace: rsmnsadsat
  labels:
    app: openshift-rabbitmq
    app.kubernetes.io/component: openshift-rabbitmq
    app.kubernetes.io/instance: openshift-rabbitmq
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
  replicas: 0
  revisionHistoryLimit: 10
  test: false
  selector:
    app: openshift-rabbitmq
    deploymentconfig: openshift-rabbitmq
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: openshift-rabbitmq
        deploymentconfig: openshift-rabbitmq
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      volumes:
        - name: openshift-rabbitmq-1
          emptyDir: {}
      containers:
        - resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 300m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          name: openshift-rabbitmq
          env:
            - name: RABBITMQ_NODENAME
              value: rabbit1@openshift-rabbitmq
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
            - name: RABBITMQ_ERLANG_COOKIE
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: cookie
          ports:
            - containerPort: 15671
              protocol: TCP
            - containerPort: 15672
              protocol: TCP
            - containerPort: 25672
              protocol: TCP
            - containerPort: 4369
              protocol: TCP
            - containerPort: 5671
              protocol: TCP
            - containerPort: 5672
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: openshift-rabbitmq-1
              mountPath: /var/lib/rabbitmq/
          terminationMessagePolicy: File
          envFrom:
            - configMapRef:
                name: rabbitmq-cfg
          image: >-
            luiscoms/openshift-rabbitmq@sha256:40dfe2c80265ee0e573c8cb1e000c4b5ec74bbbb26a933b9d1dfcc22ec956854
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
